### ISSUE TITLE
Template Buttons Not Received in Android & iOS

### ISSUE THREAD

**Issue by vishwajit76** [adiwajshing/Baileys#2376]
Template buttons are not received in Android and iOS in the latest git code. In WhatsApp Web and desktop showed.

**Comment by caiogrigoleto** [comment]
@LorranX are you using android or ios?

**Comment by LorranX** [comment]
> @LorranX are you using android or ios?

Android, i didn't get to test it on iOS, u can try use my bot here wa.me/553197645863


Use the ".play" and ".meme" commands and see what happens

**Comment by caiogrigoleto** [comment]
Os botões funcionaram, vou tentar replicar aqui no meu ver se funciona! Valeu mestre! @LorranX

**Comment by LorranX** [comment]
> Os botões funcionaram, vou tentar replicar aqui no meu ver se funciona! Valeu mestre! @LorranX 

Qualquer dúvida me chama por aqui, tamo junto

**Comment by wilsinho8** [comment]
@LorranX Como faço pra atualizar na api do salman0 pra edge?

**Comment by vishwajit76** [comment]
After adding  `viewOnce: true` at the end of your button template it's working now.

**Comment by erickmanovei** [comment]
> 

@vishwajit76 , can you post your code as example for us here?

**Comment by LZNOXP** [comment]
![Screenshot_20221201-230633_Termux](https://user-images.githubusercontent.com/72902682/205087657-16de382d-3f89-442b-a031-87477e9cb0b0.png)

**Comment by erickmanovei** [comment]
> ![Screenshot_20221201-230633_Termux](https://user-images.githubusercontent.com/72902682/205087657-16de382d-3f89-442b-a031-87477e9cb0b0.png)

Still doesnt work for me... 

My package.json is: 
"@adiwajshing/baileys": "https://github.com/adiwajshing/Baileys.git",

My connection: 

`const sock = makeWASocket({
    // version,
    printQRInTerminal: true,
    auth: state,
    patchMessageBeforeSending: msg => {
      let message = msg;
      const requiresPatch = !!(
        message.buttonsMessage ||
        // || message.templateMessage
        message.listMessage
      );
      if (requiresPatch) {
        message = {
          viewOnceMessage: {
            message: {
              messageContextInfo: {
                deviceListMetadataVersion: 2,
                deviceListMetadata: {},
              },
              ...message,
            },
          },
        };
      }

      return message;
    },
  });`

and my send message function: 

`await connection.connection.sendMessage(
      `${phoneNumber}@s.whatsapp.net`,
      // data,
      {
        text: "Hi it's a template message",
        footer: 'Hello World',
        viewOnce: true,
        templateButtons: [
          {
            index: 1,
            urlButton: {
              displayText: '⭐ Star Baileys on GitHub!',
              url: 'https://github.com/adiwajshing/Baileys',
            },
          },
          {
            index: 2,
            callButton: {
              displayText: 'Call me!',
              phoneNumber: '+1 (234) 5678-901',
            },
          },
        ],
      },
    );`

**Comment by erickmanovei** [comment]
My problem is solved. The problem was the index button param, that I was starting by zero, and the correct is starting by one.
Thanks @LZNOXP

**Comment by wilsinho8** [comment]
@LorranX no whaticket do canove, eu troquei o motor (a wweb-js pela baileys) mas não consigo visualizar listas e botões. Triste, vendo la parece não ter solução

**Comment by ilhamn2405** [comment]
> 

Dimana anda menyimpannya? Apakah di index? Saya menggunakan base case

**Comment by ilhamn2405** [comment]
> Setelah menambahkan `viewOnce: true`di akhir templat tombol, itu berfungsi sekarang.

button works fine on android thanks

**Comment by caiogrigoleto** [comment]
mine here is still not working on iOS, I have already tested these possibilities, but without success..

**Comment by erickmanovei** [comment]
> mine here is still not working on iOS, I have already tested these possibilities, but without success..

You need to update the Whatsapp installed in your phone.
Have you done this?

**Comment by caiogrigoleto** [comment]
yes, I've done it, but I haven't been successful yet...

**Comment by erickmanovei** [comment]
> templateButtons

In templateButtons array, did you start the index number with 1 or 0? You need to start with 1.
Put your code here for us to analyze.

**Comment by rawars** [comment]
If they have whatsapp closed in the IOS, the message does not arrive.

**Comment by erickmanovei** [comment]
Now it's not working anymore...
I tested in iOS and when the Whatsapp is closed, the message does not arrive. When the Whatsapp is opened, the message arrive, but without content.

**Comment by is99zsq** [comment]
> Now it's not working anymore... I tested in iOS and when the Whatsapp is closed, the message does not arrive. When the Whatsapp is opened, the message arrive, but without content.

same issue here, can see a empty msg with a timestamp in UI , but no content inside

**Comment by erickmanovei** [comment]
Any solution? Even after having inserted the viewOnce: true parameter, the problem persists. It had been resolved, but the problem returned. The message does not arrive on the cell phone when Whatsapp is not open, and when it is open, the message arrives without its content.

**Comment by mzayn** [comment]
any fix for this. already use 

`viewOnce: true`

but starting today template / button are broken again for iOS ... any solution ?

**Comment by makanSukros** [comment]
Today button / template message broken again for IOS only

**Comment by Zedmerlol** [comment]
Buttons message is broken for IOS

**Comment by jrCleber** [comment]
+1

**Comment by sekooo** [comment]
+1  is fixed this issue?

**Comment by cm-creativecentral** [comment]
+1 is fixed this issue?

**Comment by hghdo** [comment]
+1 is fixed this issue?

**Comment by caiogrigoleto** [comment]
+1 is fixed this issue?

**Comment by allegrun** [comment]
+1
